### ISSUE TITLE
Failing to publish

### ISSUE THREAD

**Issue by Ericgig** [qutip/qutip-benchmark#49]
@hodgestar 
The benchmarks are not being published to the website for a while.
Is that a bug you are familiar with?

**Comment by hodgestar** [comment]
/me digs into the logs ...

So both `qutip-benchmark` and `qutip-tutorials` use `svn export https://github.com/qutip/qutip.github.io/trunk/css` and three other similar calls to pick out pieces of the `qutip.org` web templates so that they can render their sites in the same way. They use GitHub's  svn support here as a simple way to grab parts of `qutip.github.io` without having to checkout a full commit.

On January 8th, GitHub removed svn support -- https://github.blog/2023-01-20-sunsetting-subversion-support/.

I think we can replace this use with https://git-scm.com/docs/git-sparse-checkout.

**Comment by Ericgig** [comment]
Today's benchmarks are live on the website!

**Comment by hodgestar** [comment]
Yay! :D
